# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from resources import resources


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralWidget.setObjectName("centralWidget")
        self.Multimedia = QtWidgets.QPushButton(self.centralWidget)
        self.Multimedia.setGeometry(QtCore.QRect(318, 320, 150, 150))
        self.Multimedia.setStyleSheet("#Multimedia{background:#bd74f2 url(:/images/multimedia.png)}")
        self.Multimedia.setText("")
        self.Multimedia.setObjectName("Multimedia")
        self.Camera = QtWidgets.QPushButton(self.centralWidget)
        self.Camera.setGeometry(QtCore.QRect(84, 320, 150, 150))
        self.Camera.setStyleSheet("#Camera{background:#26d8fc url(:/images/camera.png)}")
        self.Camera.setText("")
        self.Camera.setObjectName("Camera")
        self.Close = QtWidgets.QPushButton(self.centralWidget)
        self.Close.setGeometry(QtCore.QRect(786, 320, 150, 150))
        self.Close.setStyleSheet("#Close{background:#fe022c url(:/images/close.png)}")
        self.Close.setText("")
        self.Close.setObjectName("Close")
        self.Settings = QtWidgets.QPushButton(self.centralWidget)
        self.Settings.setGeometry(QtCore.QRect(552, 320, 150, 150))
        self.Settings.setStyleSheet("#Settings{background:#848484 url(:/images/settings.png)}")
        self.Settings.setText("")
        self.Settings.setObjectName("Settings")
        self.MP3_Player = QtWidgets.QPushButton(self.centralWidget)
        self.MP3_Player.setGeometry(QtCore.QRect(84, 80, 150, 150))
        self.MP3_Player.setStyleSheet("#MP3_Player{background: #ff9215 url(:/images/VLC.png)}")
        self.MP3_Player.setText("")
        self.MP3_Player.setObjectName("MP3_Player")
        self.FM_Radio = QtWidgets.QPushButton(self.centralWidget)
        self.FM_Radio.setGeometry(QtCore.QRect(318, 80, 150, 150))
        self.FM_Radio.setStyleSheet("#FM_Radio{background: #13de00 url(:/images/radio.png)}")
        self.FM_Radio.setText("")
        self.FM_Radio.setObjectName("FM_Radio")
        self.Navigation = QtWidgets.QPushButton(self.centralWidget)
        self.Navigation.setGeometry(QtCore.QRect(552, 80, 150, 150))
        self.Navigation.setStyleSheet("#Navigation{background: #ad6301 url(:/images/gps.png)}")
        self.Navigation.setText("")
        self.Navigation.setObjectName("Navigation")
        self.Camcorder = QtWidgets.QPushButton(self.centralWidget)
        self.Camcorder.setGeometry(QtCore.QRect(786, 80, 150, 150))
        self.Camcorder.setStyleSheet("#Camcorder{background:#8214d0 url(:/images/camcorder.png)}")
        self.Camcorder.setText("")
        self.Camcorder.setObjectName("Camcorder")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(84, 240, 181, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(318, 240, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(552, 240, 181, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(786, 240, 181, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(84, 480, 181, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(318, 480, 181, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(552, 480, 181, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(786, 480, 181, 31))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.Multimedia, self.Camera)
        MainWindow.setTabOrder(self.Camera, self.Close)
        MainWindow.setTabOrder(self.Close, self.Settings)
        MainWindow.setTabOrder(self.Settings, self.MP3_Player)
        MainWindow.setTabOrder(self.MP3_Player, self.FM_Radio)
        MainWindow.setTabOrder(self.FM_Radio, self.Navigation)
        MainWindow.setTabOrder(self.Navigation, self.Camcorder)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CarPi"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Odtwarzacz MP3</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Radio FM</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Nawigacja</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Kamera</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Aparat</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Multimedia</span></p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Ustawienia</span></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Zamknij</span></p><p><br/></p></body></html>"))

