# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'multimedia_window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from resources import resources


class Ui_MultimediaWindow(object):
    def setupUi(self, MultimediaWindow):
        MultimediaWindow.setObjectName("MultimediaWindow")
        MultimediaWindow.resize(1024, 540)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MultimediaWindow.sizePolicy().hasHeightForWidth())
        MultimediaWindow.setSizePolicy(sizePolicy)
        MultimediaWindow.setMouseTracking(False)
        MultimediaWindow.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MultimediaWindow.setAnimated(True)
        MultimediaWindow.setDocumentMode(False)
        MultimediaWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralWidget = QtWidgets.QWidget(MultimediaWindow)
        self.centralWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.centralWidget.setObjectName("centralWidget")
        self.Internet = QtWidgets.QPushButton(self.centralWidget)
        self.Internet.setGeometry(QtCore.QRect(318, 320, 150, 150))
        self.Internet.setStyleSheet("#Internet{background:#ececec url(:/images/google_chrome.png)}")
        self.Internet.setText("")
        self.Internet.setObjectName("Internet")
        self.Photos = QtWidgets.QPushButton(self.centralWidget)
        self.Photos.setGeometry(QtCore.QRect(84, 320, 150, 150))
        self.Photos.setStyleSheet("#Photos{background:#ff9215 url(:/images/desktop.png)}")
        self.Photos.setText("")
        self.Photos.setObjectName("Photos")
        self.Back = QtWidgets.QPushButton(self.centralWidget)
        self.Back.setGeometry(QtCore.QRect(786, 320, 150, 150))
        self.Back.setStyleSheet("#Back{background:#168c24 url(:/images/back.png)}")
        self.Back.setText("")
        self.Back.setObjectName("Back")
        self.Netflix = QtWidgets.QPushButton(self.centralWidget)
        self.Netflix.setGeometry(QtCore.QRect(552, 320, 150, 150))
        self.Netflix.setStyleSheet("#Netflix{background:#ffffff url(:/images/netflix.png)}")
        self.Netflix.setText("")
        self.Netflix.setObjectName("Netflix")
        self.Spotify = QtWidgets.QPushButton(self.centralWidget)
        self.Spotify.setGeometry(QtCore.QRect(84, 80, 150, 150))
        self.Spotify.setStyleSheet("#Spotify{background: #13de00 url(:/images/spotify.png)}")
        self.Spotify.setText("")
        self.Spotify.setObjectName("Spotify")
        self.Youtube = QtWidgets.QPushButton(self.centralWidget)
        self.Youtube.setGeometry(QtCore.QRect(318, 80, 150, 150))
        self.Youtube.setStyleSheet("#Youtube{background: #fe022c url(:/images/youtube.png)}")
        self.Youtube.setText("")
        self.Youtube.setObjectName("Youtube")
        self.TV = QtWidgets.QPushButton(self.centralWidget)
        self.TV.setGeometry(QtCore.QRect(552, 80, 150, 150))
        self.TV.setStyleSheet("#TV{background: #26d8fc url(:/images/tv.png)}")
        self.TV.setText("")
        self.TV.setObjectName("TV")
        self.Videos = QtWidgets.QPushButton(self.centralWidget)
        self.Videos.setGeometry(QtCore.QRect(786, 80, 150, 150))
        self.Videos.setStyleSheet("#Videos{background:#bd74f2 url(:/images/multimedia.png)}")
        self.Videos.setText("")
        self.Videos.setObjectName("Videos")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(84, 240, 181, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(318, 240, 181, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(552, 240, 181, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(786, 240, 181, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(84, 480, 181, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(318, 480, 181, 31))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralWidget)
        self.label_7.setGeometry(QtCore.QRect(552, 480, 181, 31))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralWidget)
        self.label_8.setGeometry(QtCore.QRect(786, 480, 181, 31))
        self.label_8.setObjectName("label_8")
        MultimediaWindow.setCentralWidget(self.centralWidget)

        self.retranslateUi(MultimediaWindow)
        self.Back.clicked.connect(MultimediaWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MultimediaWindow)
        MultimediaWindow.setTabOrder(self.Internet, self.Photos)
        MultimediaWindow.setTabOrder(self.Photos, self.Back)
        MultimediaWindow.setTabOrder(self.Back, self.Netflix)
        MultimediaWindow.setTabOrder(self.Netflix, self.Spotify)
        MultimediaWindow.setTabOrder(self.Spotify, self.Youtube)
        MultimediaWindow.setTabOrder(self.Youtube, self.TV)
        MultimediaWindow.setTabOrder(self.TV, self.Videos)

    def retranslateUi(self, MultimediaWindow):
        _translate = QtCore.QCoreApplication.translate
        MultimediaWindow.setWindowTitle(_translate("MultimediaWindow", "CarPi"))
        self.label.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Spotify</span></p><p><br/></p></body></html>"))
        self.label_2.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Youtube</span></p><p><br/></p></body></html>"))
        self.label_3.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Telewizja</span></p><p><br/></p></body></html>"))
        self.label_4.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Wideo</span></p><p><br/></p></body></html>"))
        self.label_5.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Zdjęcia</span></p><p><br/></p></body></html>"))
        self.label_6.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Google Chrome</span></p><p><br/></p></body></html>"))
        self.label_7.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Netflix</span></p><p><br/></p></body></html>"))
        self.label_8.setText(_translate("MultimediaWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Cofnij</span></p><p><br/></p></body></html>"))

